### ISSUE TITLE
Add prd (python generated directory) to PYTHONPATH

### ISSUE THREAD

**Issue by ghost** [ETSInitiative/PETSIRDUseCaseTemplate#7]
```
  "containerEnv": {
    "PYTHONPATH": "/workspaces/STIR2PETSIRD/PETSIRD/python"
  }
```
The aboce. should be added to the `.devcontainer/devcontainer.json` file.

Example implementation and use case.
https://github.com/ETSIhackers/STIR2PETSIRD/blob/52d21ad78533a2905766f16219ab4ad3caac2da4/.devcontainer/devcontainer.json#L126-L128

**Comment by KrisThielemans** [comment]
Problem is it needs the project-name. I think one of the `.bashrc` methods could be easier to, although even there people will have to rename presumably. (don't want to do an ugly `find ~ -d -name PETSIRD`).

I've created https://github.com/microsoft/yardl/issues/108 which is probably the way forward.
